############################################################################
#
### web访问端口号 约定:8088
#
############################################################################
server:
  #port: 8088
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB

############################################################################
#
###配置数据源信息
#
############################################################################
spring:
 profiles:
   active: dev
 datasource: # 数据源的相关配置
  type: com.zaxxer.hikari.HikariDataSource # 数据源类型：   HikariCP
  driver-class-name: com.mysql.jdbc.Driver # mysql驱动
#  url: jdbc:mysql://localhost:3306/foodie?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
  username: root
#  password: root
  hikari:
   connection-timeout: 30000 # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQ
   minimum-idle: 5 # 最小连接数 maximum-pool-size: 20 # 最大连接数
   auto-commit: true # 自动提交
   idle-timeout: 600000 # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
   pool-name: DateSourceHikariCP # 连接池名字
   max-lifetime: 1800000 # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟
   connection-test-query: SELECT 1
 mvc:
   pathmatch:
     matching-strategy: ant_path_matcher # swagger_ui配置
############################################################################
#
### mybatis 开启mybatis日志
#
############################################################################
mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: lamb.key.pojo # 所有pojo类所在包的路径
  mapper-locations: classpath:mapper/*.xml

# 分页插件配置
pagehelper:
 helperDialect: mysql
 supportMethodsArguments: true

#cos:
#  tencent:
#    accesskey: AKIDJRJwLWS9cqoX0DBtLYVCeqnUw84lCPN5
#    secretKey: UjiRv97sNddNs76pJXVFkzzkFUTDhvtb
#    bucket: ap-guangzhou
#    bucketName: lambkey-1309051782
#    path: https://lambkey-1309051782.cos.ap-guangzhou.myqcloud.com